In [1]:
import numpy as np #导入numpy库

In [2]:
# 利用已有数据生成数组
n1 = np.array([1,2,3]) # 将列表转换成数组，将列表换成元组也可以
n2 = np.array([[1,2],[3,4]]) # 将嵌套列表转换成多维数组
print(n1)
print(n2)
print(type(n1))

[1 2 3]
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [3]:
# 生成特定形状的多维数组
n = np.empty([2,3]) # 生成2行3列的空数组，每个元素是未初始化的垃圾值
print(n)
n1 = np.zeros([3,3]) # 生成3行3列的数组，每个元素都是0
print(n1)
n2 = np.zeros_like(n1) # 生成与n1形状一样的全0数组
print(n2)
n1 = np.ones(5) # 生成长度为5的一维数组，每个元素都是1
print(n1)
n2 = np.ones_like(n1) # 生成与n1形状一样的全1数组
print(n2)
n = np.full((4,5),3.5) # 生成4行5列的数组，每个元素都是3.5
print(n)
n = np.eye(3) # 生成3阶单位矩阵
print(n)
n = np.diag([1,2,3]) # 生成3阶对角矩阵
print(n)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[[3.5 3.5 3.5 3.5 3.5]
 [3.5 3.5 3.5 3.5 3.5]
 [3.5 3.5 3.5 3.5 3.5]
 [3.5 3.5 3.5 3.5 3.5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [4]:
# 利用arange和linspace函数生成数组
n = np.arange(start=1,stop=12,step=2) # 生成从1到12的等差数列组成的一维数组，公差为2，start默认为0，step默认为1
print(n)
n = np.arange(10)
print(n)
n = np.arange(1,4,0.5)
print(n)
n = np.arange(9,-1,-1)
print(n)
n = np.linspace(start=0,stop=1,num=10) # 生成0到1范围内一个等分数组，num数组长度默认为50
print(n)

[ 1  3  5  7  9 11]
[0 1 2 3 4 5 6 7 8 9]
[1.  1.5 2.  2.5 3.  3.5]
[9 8 7 6 5 4 3 2 1 0]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [5]:
# 利用random模块生成数组
# 生成0到1之间均匀分布的10个随机数
# np.random.seed先设置一个种子，保证生成的结果可重现
np.random.seed(312)
n = np.random.uniform(0,1,10)
print(n)
# 生成标准正态分布的9个随机数，组成3行3列的二维数组
n = np.random.randn(3,3)
print(n)
# 生成均值为1，标准差为2的正态分布的10个随机数
np.random.seed(312)
n = np.random.normal(1,2,10)
print(n)
# 生成1到10之间的10整数，组成2行5列的二维数组
np.random.seed(312)
n = np.random.randint(1,10,(2,5))
print(n)

[0.21672688 0.41872202 0.41428279 0.17027813 0.86614649 0.62067782
 0.43610476 0.68450486 0.06035922 0.92730465]
[[ 0.33631931 -0.78972444  0.92643631]
 [-0.27419659  0.77206164 -1.66094593]
 [ 1.4199694   0.69805168  0.26039679]]
[ 0.19789951 -1.79551128 -1.39790635  0.37662056  1.6384644   2.9371538
  4.66520365 -0.26928399  1.67263861 -0.57944888]
[[1 5 4 3 2]
 [4 1 3 9 7]]


In [6]:
# 数组属性
print(n.ndim) # 数组的维度数
print(n.shape) # 数组的维度长度，为一个整数元组
print(n.dtype) # 数据类型，描述数组中元素的类型
print(n.size) # 数组中有多少个元素
print(n.round(2)) # 数组中每个元素保留小数点后两位

2
(2, 5)
int32
10
[[1 5 4 3 2]
 [4 1 3 9 7]]


In [7]:
# 抽取数组元素
np.random.seed(2024)
n = np.random.random(10) #生成0到1之间的10个随机数
print(n)
print(n[0]) # 获取第一个元素
print(n[-2]) # 获取倒数第二个元素
print(n[0:2]) # 获取一段数据
print(n[:4])
print(n[1:])
print(n[:]) # 获取所有元素
n = np.arange(25).reshape(5,5)
print(n)
print(n[1:3,1:3]) # 获取多维数组中某个区域内的数据
print(n[(n>3)&(n<10)]) # 获取多维数组中数值在某个值域内的数据
print(n[[1,2],:]) # 获取多维数组中指定的行
print(n[1:4,:]) 
print(n[:,2:]) # 获取多维数组中指定的列
n = np.arange(1,25,dtype=float)
print(n)
n1 = np.random.choice(n,size=(3,4)) # 从n中随机抽取元素组成指定形状的数组，默认为有放回抽样
print(n1)
n2 = np.random.choice(n,size=(3,4),replace=False) # 从n中随机抽取元素组成指定形状的数组，replace=False代表无放回抽样
print(n2)
n3 = np.random.choice(n,size=(3,4),p=n/np.sum(n)) # 从n中随机抽取元素组成指定形状的数组，p指定n每个元素被抽取的概率，默认为相同概率抽样
print(n3)

[0.58801452 0.69910875 0.18815196 0.04380856 0.20501895 0.10606287
 0.72724014 0.67940052 0.4738457  0.44829582]
0.5880145188953979
0.4738457034082185
[0.58801452 0.69910875]
[0.58801452 0.69910875 0.18815196 0.04380856]
[0.69910875 0.18815196 0.04380856 0.20501895 0.10606287 0.72724014
 0.67940052 0.4738457  0.44829582]
[0.58801452 0.69910875 0.18815196 0.04380856 0.20501895 0.10606287
 0.72724014 0.67940052 0.4738457  0.44829582]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 6  7]
 [11 12]]
[4 5 6 7 8 9]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24.]
[[16. 24. 11. 15.]
 [16. 12.  8. 23.]
 [19. 24. 10.  7.]]
[[ 3. 17. 12. 19.]
 [ 7. 15.  4. 10.]
 [14. 13. 24. 18.]]
[[ 5. 21. 15.  9.]
 [19.  5. 23. 23.]
 [23. 24. 21. 10.]]


In [8]:
# NumPy的算术运算
# 逐元素运算是两个矩阵中对应元素的运算，输出数组与输入数组大小一致
n1 = np.array([[1,2],[-1,4]])
n2 = np.array([[2,0.2],[3,4]])
print(n1)
print(n2)
print(n1+n2)
print(n1-n2)
print(n1*n2)
print(n1/n2)
print(n1**n2)
print(n1*100)

[[ 1  2]
 [-1  4]]
[[2.  0.2]
 [3.  4. ]]
[[3.  2.2]
 [2.  8. ]]
[[-1.   1.8]
 [-4.   0. ]]
[[ 2.   0.4]
 [-3.  16. ]]
[[ 0.5        10.        ]
 [-0.33333333  1.        ]]
[[  1.           1.14869835]
 [ -1.         256.        ]]
[[ 100  200]
 [-100  400]]


In [9]:
n=np.array([['A',100],['B',200],['C',300],['D',400]])
print(n)
print(n.transpose())

[['A' '100']
 ['B' '200']
 ['C' '300']
 ['D' '400']]
[['A' 'B' 'C' 'D']
 ['100' '200' '300' '400']]


In [10]:
print(n.flatten())
print(n.flatten(order="F"))

['A' '100' 'B' '200' 'C' '300' 'D' '400']
['A' 'B' 'C' 'D' '100' '200' '300' '400']


In [11]:
n1=np.array([[1,2],[3,4],[5,6]])
n2=np.array([[10,20],[30,40],[50,60]])
print(n1)
print(n2)
print(np.hstack((n1,n2)))
print(np.vstack((n1,n2)))

[[1 2]
 [3 4]
 [5 6]]
[[10 20]
 [30 40]
 [50 60]]
[[ 1  2 10 20]
 [ 3  4 30 40]
 [ 5  6 50 60]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [10 20]
 [30 40]
 [50 60]]


In [12]:
np.random.seed(312)
n=np.random.normal(1,2,(3,8))
print(n)

[[ 0.19789951 -1.79551128 -1.39790635  0.37662056  1.6384644   2.9371538
   4.66520365 -0.26928399]
 [ 1.67263861 -0.57944888  2.85287262  0.45160683  2.54412329 -2.32189185
   3.83993881  2.39610336]
 [ 1.52079358 -0.17077611  2.31968888 -1.05851569  2.40258142 -2.22289737
  -0.06796161  0.71552633]]


In [13]:
print(np.sum(n))
print(np.sum(n,axis=0))
print(np.sum(n,axis=1))

20.647022518983203
[ 3.3913317  -2.54573627  3.77465515 -0.2302883   6.58516911 -1.60763541
  8.43718085  2.84234569]
[ 6.3526403  10.85594277  3.43843944]


In [14]:
print(np.absolute(n))
print(np.mean(n))
print(np.max(n))
print(np.min(n))
print(np.argmax(n))
print(np.argmin(n))
print(np.median(n))
print(np.var(n))
print(np.std(n))

[[0.19789951 1.79551128 1.39790635 0.37662056 1.6384644  2.9371538
  4.66520365 0.26928399]
 [1.67263861 0.57944888 2.85287262 0.45160683 2.54412329 2.32189185
  3.83993881 2.39610336]
 [1.52079358 0.17077611 2.31968888 1.05851569 2.40258142 2.22289737
  0.06796161 0.71552633]]
0.8602926049576335
4.6652036463951685
-2.3218918531626076
6
13
0.5835665764739222
3.526865044994493
1.8779949533996338
